    {
      id: '10',
      name: 'Street Fight',
      url: 'https://www.gamepix.com/play/street-fight',
      description: 'Master classic combat in the world warrior tournament cabinet.',
      genre: 'Fighting',
      rating: 4.7,
      playersOnline: 4500,
      availability: 'Online',
      tags: ['Combat', 'Arcade', 'Versus', 'Multiplayer', 'station-cabinet'],
      badgeIds: ['tournament-live'],
      queueEstimateMinutes: 2,
      sessionObjectives: [
        'Win one set without dropping a round',
        'Land a clean punish combo',
      ],
      controlHints: ['Block low on wake-up', 'Buffer inputs during jumps'],
      launchConfig: {
        difficulty: 'Bracket',
        controls: ['Keyboard'],
        objectives: [
          'Survive the first bracket round',
          'Convert one punish cleanly',
        ],
        modes: ['Solo', 'Versus'],
        inlinePolicy: 'trusted',
        trustNote: 'Allowlisted retro combat partner.',
        embedMode: 'inline',
        approvedExternalUrl: 'https://www.gamepix.com/play/street-fight',
        approvedEmbedUrl: 'https://www.gamepix.com/play/street-fight',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://www.gamepix.com'],
      },
      art: {
        eyebrow: 'Combat',
        accentStart: '#f97316',
        accentEnd: '#c2410c',
      },
      multiplayerType: 'Server',
    },
