import { ThaSpotFeed } from './game';

export const THA_SPOT_FALLBACK_FEED: ThaSpotFeed = {
  badges: [
    { id: 'featured', label: 'Featured', tone: 'primary' },
    { id: 'trending', label: 'Trending', tone: 'secondary' },
    { id: 'staff-pick', label: 'Staff Pick', tone: 'accent' },
    { id: 'new-drop', label: 'New Drop', tone: 'warning' },
    { id: 'tournament-live', label: 'Tournament Live', tone: 'secondary' },
  ],
  rooms: [
    {
      id: 'all',
      name: 'All Games',
      icon: 'grid_view',
      description: 'Fallback arcade roster while the live feed reconnects.',
    },
    {
      id: 'arcade',
      name: 'Arcade',
      icon: 'joystick',
      description: 'Fast starts, quick resets, and reactive cabinet runs.',
      rules: { tags: ['Arcade', 'Reflex'] },
    },
    {
      id: 'sports',
      name: 'Sports',
      icon: 'sports_basketball',
      description:
        'Competitive sports runs with quick rematches and bracket pace.',
      rules: { genres: ['Sports'] },
    },
    {
      id: 'fighting-pit',
      name: 'Fighting',
      icon: 'sports_mma',
      description:
        'Combo-heavy cabinets with head-to-head pressure and fight-night energy.',
      rules: { genres: ['Fighting'] },
    },
    {
      id: 'shooting-range',
      name: 'Shooting',
      icon: 'my_location',
      description:
        'Tactical shooter lanes built for quick co-op drops and aim drills.',
      rules: { genres: ['Shooting'] },
    },
    {
      id: 'rpg-vault',
      name: 'RPG',
      icon: 'shield',
      description:
        'Progression-focused adventures and raid loops while the live feed reconnects.',
      rules: { tags: ['RPG'] },
    },
    {
      id: 'co-op-link',
      name: 'Online Co-op',
      icon: 'groups',
      description: 'Squad-ready fallback picks for shared online objectives.',
      rules: { tags: ['Co-op'] },
    },
    {
      id: 'strategy',
      name: 'Strategy',
      icon: 'psychology',
      description: 'Puzzle and board-first play tuned for thinkers.',
      rules: { genres: ['Strategy', 'Puzzle', 'Classic'] },
    },
  ],
  liveEvents: [
    {
      id: 'fallback-showdown',
      title: 'Fallback Floor Challenge',
      description: 'Queue up while Tha Spot refreshes the live schedule.',
      roomId: 'arcade',
      reward: 'Featured cosmetic',
      status: 'live',
      windowLabel: 'Live now',
      badgeId: 'tournament-live',
      featuredGameId: '1',
      schedule: {
        startAt: '2026-04-01T18:00:00.000Z',
        endAt: '2026-04-30T23:59:59.000Z',
        recurrence: 'once',
        rewardType: 'cosmetic',
      },
    },
    {
      id: 'fallback-squad-link',
      title: 'Fallback squad sync',
      description:
        'Online co-op lobbies stay warm even while the main feed reconnects.',
      roomId: 'co-op-link',
      reward: 'Squad sync token',
      status: 'upcoming',
      windowLabel: 'Starts soon',
      badgeId: 'featured',
      featuredGameId: '9',
      schedule: {
        startAt: '2026-04-01T20:00:00.000Z',
        endAt: '2026-04-30T23:59:59.000Z',
        recurrence: 'daily',
        rewardType: 'token',
      },
    },
  ],
  socialPresence: [
    {
      id: 'fallback-1',
      name: 'StudioGhost',
      status: 'hosting',
      activity: 'Hosting a reflex warmup room',
      roomId: 'arcade',
      gameId: '1',
      relationship: 'friend',
      joinable: true,
      cta: 'Join friend',
    },
    {
      id: 'fallback-2',
      name: 'ExecutiveGrid',
      status: 'invited',
      activity: 'Party invite waiting in Grandmaster Chess',
      roomId: 'strategy',
      gameId: '3',
      relationship: 'invite',
      pendingInvite: true,
      partySize: 2,
      cta: 'Accept invite',
      alert: 'Invite expires soon.',
    },
    {
      id: 'fallback-3',
      name: 'ComboRelay',
      status: 'queueing',
      activity: 'Queued for a Street Brawler V set',
      roomId: 'fighting-pit',
      gameId: '6',
      relationship: 'rival',
      joinable: true,
      cta: 'Track rival',
      alert: 'Fight card opens in a minute.',
    },
    {
      id: 'fallback-4',
      name: 'RaidSignal',
      status: 'hosting',
      activity: 'Hosting a Mythic Raid Online squad lobby',
      roomId: 'co-op-link',
      gameId: '9',
      relationship: 'party',
      joinable: true,
      partySize: 4,
      cta: 'Join squad',
      alert: 'Party voice sync is live.',
    },
  ],
  promotions: [
    {
      id: 'promo-studio',
      title: 'Jump back into Studio',
      description:
        'Carry the energy from Tha Spot into a new production session.',
      route: '/studio',
      icon: 'tune',
      cta: 'Open Studio',
      roomIds: ['arcade'],
      audienceTags: ['returning', 'producer'],
      priority: 8,
      campaignType: 'studio',
    },
    {
      id: 'promo-intel',
      title: 'Open the Intel stack',
      description: 'Review live room data and plan your next move.',
      route: '/strategy',
      icon: 'analytics',
      cta: 'Open Intel',
      roomIds: ['strategy'],
      audienceTags: ['competitive'],
      priority: 7,
      campaignType: 'intel',
    },
  ],
  recommendationRails: [
    {
      id: 'fallback-returning',
      title: 'Warm restart picks',
      subtitle: 'Use your last sessions to snap back into flow.',
      audience: { minPlays: 1, maxPlays: 999 },
      roomIds: ['all'],
      weights: {
        history: 16,
        crowd: 4,
        badge: 3,
        novelty: 1,
        room: 2,
        genre: 6,
      },
      maxItems: 4,
    },
    {
      id: 'fallback-producer',
      title: 'Producer crossover',
      subtitle: 'Rhythm and puzzle cabinets that fit studio downtime.',
      audience: { primaryGenres: ['Hip Hop', 'R&B', 'Pop'] },
      roomIds: ['arcade', 'strategy'],
      weights: {
        genre: 14,
        history: 5,
        crowd: 3,
        badge: 4,
        novelty: 2,
        room: 4,
      },
      maxItems: 4,
    },
    {
      id: 'fallback-competitive',
      title: 'Competitive fallback',
      subtitle:
        'Fight-night, shooter, and sports picks stay visible during reconnects.',
      audience: {
        minPlays: 0,
        maxPlays: 999,
        rooms: ['sports', 'fighting-pit', 'shooting-range'],
      },
      roomIds: ['sports', 'fighting-pit', 'shooting-range'],
      weights: {
        genre: 8,
        history: 7,
        crowd: 6,
        badge: 4,
        novelty: 2,
        room: 8,
      },
      maxItems: 4,
    },
    {
      id: 'fallback-coop',
      title: 'Squad fallback',
      subtitle: 'Co-op and RPG cabinets that keep party play active offline.',
      audience: {
        minPlays: 0,
        maxPlays: 999,
        rooms: ['co-op-link', 'rpg-vault'],
      },
      roomIds: ['co-op-link', 'rpg-vault'],
      weights: {
        genre: 6,
        history: 6,
        crowd: 5,
        badge: 4,
        novelty: 3,
        room: 9,
      },
      maxItems: 4,
    },
  ],
  games: [
    {
      id: '1',
      name: 'Neon Drift X',
      url: '/assets/games/neon-drift/neon-drift.html',
      description: 'Precision traffic runs with instant offline recovery.',
      genre: 'Racing',
      rating: 4.8,
      playersOnline: 420,
      availability: 'Offline',
      tags: ['Arcade', 'Offline', 'Reflex'],
      badgeIds: ['featured'],
      queueEstimateMinutes: 0,
      sessionObjectives: [
        'Survive 90 seconds',
        'Finish a flawless lane swap chain',
      ],
      controlHints: [
        'Arrow keys to weave lanes',
        'Stay centered before boosts',
      ],
      launchConfig: {
        difficulty: 'Medium',
        objectives: ['Survive the first wave', 'Keep a clean run going'],
        controls: ['Arrow keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/neon-drift/neon-drift.html',
        approvedExternalUrl: '/assets/games/neon-drift/neon-drift.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'Offline',
        accentStart: '#38bdf8',
        accentEnd: '#6366f1',
      },
    },
    {
      id: '2',
      name: 'Tempo Lockdown',
      url: '/assets/games/tempo-lockdown/tempo-lockdown.html',
      description: 'A responsive offline rhythm lane for short focus sprints.',
      genre: 'Rhythm',
      rating: 4.8,
      playersOnline: 390,
      availability: 'Offline',
      tags: ['Rhythm', 'Arcade', 'Original'],
      badgeIds: ['staff-pick'],
      queueEstimateMinutes: 0,
      sessionObjectives: ['Hold a clean note chain', 'Stay above 95% timing'],
      controlHints: ['Use the displayed lane keys', 'Anticipate sync shifts'],
      launchConfig: {
        difficulty: 'Adaptive',
        objectives: ['Keep the meter green', 'Trigger a perfect run'],
        controls: ['Lane keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/tempo-lockdown/tempo-lockdown.html',
        approvedExternalUrl: '/assets/games/tempo-lockdown/tempo-lockdown.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'Offline',
        accentStart: '#34d399',
        accentEnd: '#059669',
      },
    },
    {
      id: '3',
      name: 'Grandmaster Chess',
      url: 'https://poki.com/en/g/master-chess',
      description:
        'Long-form strategy sessions with a steady competitive queue.',
      genre: 'Strategy',
      rating: 4.9,
      playersOnline: 32400,
      availability: 'Online',
      tags: ['Strategy', 'Logic', 'Classic'],
      badgeIds: ['trending'],
      queueEstimateMinutes: 1,
      sessionObjectives: [
        'Win material by move 15',
        'Convert one endgame cleanly',
      ],
      controlHints: [
        'Open the center early',
        'Review checks, captures, threats',
      ],
      launchConfig: {
        difficulty: 'Ranked',
        objectives: ['Hold tempo', 'Finish with a clean conversion'],
        controls: ['Mouse'],
        modes: ['Solo', 'Versus'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://poki.com/en/g/master-chess',
        approvedExternalUrl: 'https://poki.com/en/g/master-chess',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://poki.com'],
      },
      art: {
        eyebrow: 'Strategy',
        accentStart: '#f8fafc',
        accentEnd: '#1e293b',
      },
    },
    {
      id: '4',
      name: 'Cipher Surge',
      url: '/assets/games/cipher-surge/cipher-surge.html',
      description:
        'Offline neural pattern-defense game with polished AI memory rounds and instant retries.',
      genre: 'Puzzle',
      rating: 4.8,
      playersOnline: 510,
      availability: 'Offline',
      tags: ['Puzzle', 'AI', 'Original', 'Logic'],
      badgeIds: ['new-drop', 'staff-pick'],
      queueEstimateMinutes: 0,
      sessionObjectives: [
        'Clear five neural rounds',
        'Finish with at least 70% integrity',
      ],
      controlHints: [
        'Watch the full sequence before reacting',
        'Prioritize rhythm over speed on longer chains',
      ],
      launchConfig: {
        difficulty: 'Adaptive',
        objectives: [
          'Hold integrity above 70%',
          'Perfect one full pattern chain',
        ],
        controls: ['Mouse or touch'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: '/assets/games/cipher-surge/cipher-surge.html',
        approvedExternalUrl: '/assets/games/cipher-surge/cipher-surge.html',
        telemetryMode: 'frame-only',
      },
      art: {
        eyebrow: 'AI Puzzle',
        accentStart: '#8b5cf6',
        accentEnd: '#4c1d95',
      },
    },
    {
      id: '5',
      name: 'Pac-Man Classic',
      url: 'https://pacman.live/play.html',
      description:
        'High-quality retro cabinet with polished route play and instant arcade readability.',
      genre: 'Classic',
      rating: 4.9,
      playersOnline: 15400,
      availability: 'Online',
      tags: ['Classic', 'Arcade', 'Retro'],
      badgeIds: ['trending'],
      queueEstimateMinutes: 0,
      sessionObjectives: ['Clear two boards', 'Bank one ghost combo'],
      controlHints: [
        'Use corners for ghost control',
        'Commit to power-pellet routes',
      ],
      launchConfig: {
        difficulty: 'Classic',
        objectives: ['Beat your route time', 'Convert a full power cycle'],
        controls: ['Arrow keys'],
        modes: ['Solo'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://pacman.live/play.html',
        approvedExternalUrl: 'https://pacman.live/play.html',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://pacman.live'],
      },
      art: {
        eyebrow: 'Retro',
        accentStart: '#facc15',
        accentEnd: '#eab308',
      },
    },
    {
      id: '6',
      name: 'Street Brawler V',
      url: 'https://www.gamepix.com/play/street-fight',
      description:
        'Fallback fight-night cabinet with clean combos, short queues, and versus pressure.',
      genre: 'Fighting',
      rating: 4.7,
      playersOnline: 4500,
      availability: 'Online',
      tags: ['Fighting', 'Combat', 'Versus', 'Multiplayer'],
      badgeIds: ['tournament-live'],
      queueEstimateMinutes: 2,
      multiplayerType: 'Server',
      sessionObjectives: [
        'Win a set without dropping neutral',
        'Land one punish combo cleanly',
      ],
      controlHints: [
        'Block on wake-up before taking space',
        'Buffer inputs during jumps',
      ],
      launchConfig: {
        difficulty: 'Bracket',
        objectives: [
          'Survive one fight card round',
          'Convert one punish cleanly',
        ],
        controls: ['Keyboard'],
        modes: ['Versus'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://www.gamepix.com/play/street-fight',
        approvedExternalUrl: 'https://www.gamepix.com/play/street-fight',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://www.gamepix.com'],
      },
      art: {
        eyebrow: 'Fight Night',
        accentStart: '#f97316',
        accentEnd: '#c2410c',
      },
    },
    {
      id: '7',
      name: 'Super Bowling Pro',
      url: 'https://www.gamepix.com/play/classic-bowling',
      description:
        'Reliable fallback sports cabinet with tournament pacing and precision lineups.',
      genre: 'Sports',
      rating: 4.6,
      playersOnline: 4200,
      availability: 'Online',
      tags: ['Sports', 'Bowling', 'Competitive'],
      badgeIds: ['featured'],
      queueEstimateMinutes: 1,
      sessionObjectives: [
        'String two strikes together',
        'Close one frame with a clean spare',
      ],
      controlHints: [
        'Use a consistent release lane',
        'Feather spin instead of forcing power',
      ],
      launchConfig: {
        difficulty: 'Moderate',
        objectives: [
          'Control your line through ten frames',
          'Protect your split conversions',
        ],
        controls: ['Touch', 'Mouse'],
        modes: ['Solo', 'Tournament'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://www.gamepix.com/play/classic-bowling',
        approvedExternalUrl: 'https://www.gamepix.com/play/classic-bowling',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://www.gamepix.com'],
      },
      art: {
        eyebrow: 'Sports',
        accentStart: '#38bdf8',
        accentEnd: '#1d4ed8',
      },
    },
    {
      id: '8',
      name: 'Tactical Squad',
      url: 'https://www.gamepix.com/play/tactical-squad',
      description:
        'Fallback tactical shooter with online squad lanes, breach timing, and quick redeploys.',
      genre: 'Shooting',
      rating: 4.8,
      playersOnline: 15000,
      availability: 'Online',
      tags: ['Shooting', 'Action', 'Tactical', 'Multiplayer', 'Co-op'],
      badgeIds: ['featured'],
      queueEstimateMinutes: 3,
      multiplayerType: 'Server',
      sessionObjectives: [
        'Clear one breach without losing the squad lead',
        'Hold an extraction lane for 60 seconds',
      ],
      controlHints: [
        'Reload on cover transitions',
        'Hold angles instead of chasing solo picks',
      ],
      launchConfig: {
        difficulty: 'Hard',
        objectives: [
          'Extract with the squad alive',
          'Hold one tactical objective room',
        ],
        controls: ['Keyboard', 'Mouse'],
        modes: ['Co-op', 'Squad Ops'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://www.gamepix.com/play/tactical-squad',
        approvedExternalUrl: 'https://www.gamepix.com/play/tactical-squad',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://www.gamepix.com'],
      },
      art: {
        eyebrow: 'Squad Fire',
        accentStart: '#06b6d4',
        accentEnd: '#164e63',
      },
    },
    {
      id: '9',
      name: 'Mythic Raid Online',
      url: 'https://www.gamepix.com/play/mythic-raid-online',
      description:
        'Action RPG fallback cabinet with online raid loops, loot drops, and party roles.',
      genre: 'RPG',
      rating: 4.8,
      playersOnline: 14600,
      availability: 'Hybrid',
      tags: ['RPG', 'Adventure', 'Co-op', 'Multiplayer'],
      badgeIds: ['staff-pick'],
      queueEstimateMinutes: 2,
      multiplayerType: 'Server',
      sessionObjectives: [
        'Clear one dungeon wing',
        'Keep the full party alive through a boss phase',
      ],
      controlHints: [
        'Stack cooldowns around boss mechanics',
        'Anchor the party around one support player',
      ],
      launchConfig: {
        difficulty: 'Raid',
        objectives: [
          'Finish one online dungeon',
          'Upgrade one relic before the boss room',
        ],
        controls: ['Keyboard', 'Mouse'],
        modes: ['Co-op', 'Raid', 'Adventure'],
        embedMode: 'inline',
        approvedEmbedUrl: 'https://www.gamepix.com/play/mythic-raid-online',
        approvedExternalUrl: 'https://www.gamepix.com/play/mythic-raid-online',
        telemetryMode: 'origin',
        telemetryOrigins: ['https://www.gamepix.com'],
      },
      art: {
        eyebrow: 'Raid RPG',
        accentStart: '#8b5cf6',
        accentEnd: '#4c1d95',
      },
    },
  ],
};
